# Generated by Django 5.0.3 on 2024-03-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='Sunday', max_length=10),
        ),
    ]
