# Generated by Django 5.0.3 on 2024-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0002_alter_availability_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=10),
        ),
    ]
