# Generated by Django 5.0.3 on 2024-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0006_alter_lecture_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
